### ISSUE TITLE
AssertionError: failed to binarize for XLM the file

### ISSUE THREAD

**Issue by Eduardo95** [facebookresearch/TransCoder#24]
Hi,

We I try to run the pipeline, I got this AssertionError indicating that I failed to binarize for XLM the file.
AssertionError: failed to binarize for XLM the file

I don't why this may happen, and I tried to read the source codes, but couldn't find a clue. Can anyone help me out?

Thank you.

**Comment by IgWod** [comment]
Hi,

I know it's a bit old issue, but here is a solution for anyone facing the problem in the future.

If you get a following error:

```
AssertionError: failed to binarize for XLM the file /home/xxx/TransCoder/data/test_dataset/cpp-java-python/cpp.train.3.bpe                                                                                                                   
 command: python /home/xxx/TransCoder/XLM/preprocess.py /home/xxx/TransCoder/data/test_dataset/cpp-java-python/vocab /home/xxx/TransCoder/data/test_dataset/cpp-java-python/cpp.train.3.bpe
 ````

The problem maybe the version of Python interpreter in your system. The `utils.py` script calls `python` to binarize the data, however it's likely that in your system `python` calls the 2.7 interpreter rather than 3.x. so the command fails.

An easy fix involves modifying `preprocessing/src/utils.py` to use `python3`:

```
def binarize_for_XLM_file(file_path, vocab):
    process = subprocess.run(f"python3 {XLM_PP} {vocab} {file_path}",
                             shell=True,
                             stdout=subprocess.PIPE,
                             stderr=subprocess.PIPE)
    assert Path(f'{file_path}.pth').is_file and process.returncode == 0, f"failed to binarize for XLM the file {file_path} \n command: python3 {XLM_PP} {vocab} {file_path} "
```

**Comment by malachaux** [comment]
This repo is now deprecated. Please now refer to our new repository https://github.com/facebookresearch/CodeGen
